### ISSUE TITLE
UBI Base Image

### ISSUE THREAD

**Issue by hairmare** [adfinis/scrubbed#12]
We should use [Red Hat Universal Base Images](https://catalog.redhat.com/software/base-images) as the base of our published images. I think this could ease integration/adoption of the scrubber in several cases.

The definition of done of this issue would be that we are somewhat ready to pass [preflight](https://github.com/redhat-openshift-ecosystem/openshift-preflight) on the container image.

**Comment by alesz** [comment]
fixed
